/* ============================================================================
 * light-find.js — "Light Find" 선택 폼 동작
 *
 * 동작 (Figma: 5851:2090 = Project 선택 / 5851:2304 = Space 선택 상태):
 *   단계별로 "어느 버튼이든" 누르면 → 그 버튼이 선택(검은 배경 + 흰 글자/아이콘)
 *   되고 이전 선택은 해제(단일 선택)되며, 다음 단계가 열립니다.
 *     1) Project type 선택 → 2단계(Space type) 열림   (.is-space-active)
 *     2) Space type   선택 → 3단계(Lighting type) 열림 (.is-lighting-active)
 *     3) Lighting type 선택 → 하이라이트만 (다음 화면 디자인 없음)
 *   각 단계 활성화 시 해당 제목·앞 화살표가 활성색으로 바뀌고 옵션 목록이
 *   노출됩니다(실제 색/노출 규칙은 css/pages/light-find.css 에 있음).
 *
 * 정직 고지:
 *   · Space/Lighting 옵션 목록은 Figma 가 Residential·Bedroom 기준만 제공해,
 *     어떤 상위 단계를 골라도 동일 목록을 보여줍니다(요청: "다른 버튼도 똑같이").
 *   · Lighting type 선택 후의 화면(NEXT 활성 등)은 디자인이 없어 NEXT 는
 *     정적 비활성으로 둡니다.
 * ========================================================================== */
(function () {
  "use strict";

  var steps = document.querySelector(".lf-steps");
  if (!steps) return;

  // 한 그룹(.lf-options) 안에서 단일 선택을 구현하는 헬퍼
  function wireSingleSelect(container, onSelect) {
    if (!container) return;
    var options = container.querySelectorAll(".lf-option");
    options.forEach(function (btn) {
      if (btn.disabled) return;                 // 비활성(예: Retail)은 제외
      btn.setAttribute("aria-pressed", "false");
      btn.addEventListener("click", function () {
        options.forEach(function (o) {
          o.classList.remove("is-selected");
          if (!o.disabled) o.setAttribute("aria-pressed", "false");
        });
        btn.classList.add("is-selected");
        btn.setAttribute("aria-pressed", "true");
        if (typeof onSelect === "function") onSelect(btn);
      });
    });
  }

  var projectOptions = steps.querySelector(".lf-step--1 .lf-options");
  var venueWrap = steps.querySelector(".lf-step--venue .lf-options");
  var spaceWrap = steps.querySelector(".lf-step--2 .lf-options");
  var lightingWrap = steps.querySelector(".lf-step--3 .lf-options");
  var spaceN = steps.querySelector("[data-step-space]");      // Space 단계 번호 칩(2 또는 3)
  var lightingN = steps.querySelector("[data-step-lighting]"); // Lighting 단계 번호 칩(3 또는 4)
  var next = steps.querySelector(".lf-next");

  // 프로젝트별 옵션 데이터(light-find-options.js). 정의된 프로젝트는 Space/Lighting
  // 단계를 이 데이터로 동적 렌더하고, 없는 프로젝트는 기존 정적 마크업을 복원한다.
  var PROJECTS = window.LF_PROJECTS || {};
  var defaultSpacesHTML = spaceWrap ? spaceWrap.innerHTML : "";
  var defaultLightingHTML = lightingWrap ? lightingWrap.innerHTML : "";

  function labelOf(el) {
    var l = el && el.querySelector(".lf-option__label");
    return l ? l.textContent.trim() : "";
  }
  function selectedLabel(container) {
    return labelOf(container && container.querySelector(".lf-option.is-selected"));
  }
  function esc(s) {
    return String(s == null ? "" : s)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  }
  // 알고리즘 추천 항목(예: Workspace 의 "Select a type") 클릭 시 하단에 뜨는 안내문(영문).
  var ALGO_NOTE = "General lighting recommendations generated by algorithm";

  // icon 은 신뢰된 인라인 SVG 문자열(옵션 데이터에서 옴) → escape 하지 않는다.
  // 아이콘이 있으면 기존 정적 옵션과 동일하게 .lf-option__icon + 라벨 순으로 렌더.
  // muted: PDF 에서 흐리게(grey) 표시된 항목 — Office 비활성과 같은 회색이지만
  //   클릭은 가능(disabled 아님). disabled 와 동시 사용 안 함.
  function optBtn(label, disabled, note, icon, muted) {
    return '<button type="button" class="lf-option' + (muted ? " lf-option--muted" : "") + '"' +
      (disabled ? ' disabled aria-disabled="true"' : "") +
      (note ? ' data-lf-note="' + esc(note) + '"' : "") + ">" +
      (icon || "") +
      '<span class="lf-option__label">' + esc(label) + "</span></button>";
  }
  // Venue 단계(Museum / Gallery 전용) 옵션 렌더.
  function renderVenues(cfg) {
    if (!venueWrap) return;
    venueWrap.innerHTML = (cfg.venues || []).map(function (v) {
      return optBtn(v.label, !!v.disabled, null, v.icon, !!v.muted);
    }).join("");
  }
  function renderSpaces(cfg) {
    spaceWrap.innerHTML = cfg.spaces.map(function (s) {
      return optBtn(s.label, !!s.disabled, null, s.icon, !!s.muted);
    }).join("");
  }
  function renderLighting(space) {
    var icons = window.LF_LIGHT_ICONS || {};   // 라벨 → 인라인 SVG 아이콘
    var parts = ['<p class="lf-group-head">General light</p>'];
    (space.general || []).forEach(function (o) {
      parts.push(optBtn(o.label, !!o.disabled, o.algorithm ? ALGO_NOTE : null, o.icon || icons[o.label], !!o.muted));
    });
    // Additional light 그룹은 항목이 있을 때만(예: Museum 은 Additional 없음).
    if ((space.additional || []).length) {
      parts.push('<p class="lf-group-head">Additional light</p>');
      (space.additional || []).forEach(function (o) { parts.push(optBtn(o.label, !!o.disabled, null, o.icon || icons[o.label], !!o.muted)); });
    }
    // 알고리즘 안내문 자리(기본 숨김) — 알고리즘 항목 선택 시 노출
    parts.push('<p class="lf-algo-note" data-lf-algo-note hidden></p>');
    lightingWrap.innerHTML = parts.join("");
  }

  function disableNext() {
    if (!next) return;
    next.disabled = true;
    next.setAttribute("aria-disabled", "true");
    next.classList.remove("is-active");
  }
  function enableNext() {
    if (!next) return;
    next.disabled = false;
    next.removeAttribute("aria-disabled");
    next.classList.add("is-active");
  }

  // 3) Lighting type 선택 → 필수 3단계 완료 → NEXT 활성화.
  //    알고리즘 항목(data-lf-note) 선택 시 하단 안내문 노출, 그 외엔 숨김.
  function wireLighting() {
    wireSingleSelect(lightingWrap, function (btn) {
      enableNext();
      var noteEl = lightingWrap.querySelector("[data-lf-algo-note]");
      if (!noteEl) return;
      var note = btn.getAttribute("data-lf-note");
      if (note) { noteEl.textContent = note; noteEl.hidden = false; }
      else { noteEl.textContent = ""; noteEl.hidden = true; }
    });
  }
  // 2) Space type 선택 → (config 있으면) 해당 공간 조명 목록 렌더 후 다음 단계 열기
  function wireSpaces() {
    wireSingleSelect(spaceWrap, function () {
      var cfg = PROJECTS[selectedLabel(projectOptions)];
      if (cfg) {
        var picked = selectedLabel(spaceWrap), space = null;
        for (var i = 0; i < cfg.spaces.length; i++) {
          if (cfg.spaces[i].label === picked) { space = cfg.spaces[i]; break; }
        }
        if (space) renderLighting(space);
      }
      disableNext();
      steps.classList.add("is-lighting-active");
      wireLighting();
    });
  }

  // 1.5) Venue type 선택(Museum / Gallery) → 공간 목록 렌더 후 Space 단계 열기.
  //   공간/조명 목록은 venue 와 무관(동일). venue 는 NEXT 시 위저드로 전달돼 상세
  //   흐름(Mood)에서 사용된다(Gallery 는 Focus 비활성).
  function wireVenues() {
    wireSingleSelect(venueWrap, function () {
      var cfg = PROJECTS[selectedLabel(projectOptions)];
      if (cfg) renderSpaces(cfg);
      if (lightingWrap) lightingWrap.innerHTML = defaultLightingHTML; // 조명 단계 초기화
      steps.classList.remove("is-lighting-active");
      disableNext();
      steps.classList.add("is-space-active");
      wireSpaces();
    });
  }

  // 1) Project type 선택 → (venue 있으면) Venue 단계, 없으면 Space 단계 열기
  wireSingleSelect(projectOptions, function (btn) {
    var cfg = PROJECTS[labelOf(btn)];
    // 모든 후속 단계 상태 초기화
    steps.classList.remove("is-space-active", "is-lighting-active", "is-venue-active", "has-venue");
    if (lightingWrap) lightingWrap.innerHTML = defaultLightingHTML; // 조명 단계 초기화(닫힘)
    disableNext();

    var hasVenue = !!(cfg && cfg.venues && cfg.venues.length);
    if (hasVenue) {
      // 4단계 흐름: Project → Venue → Space → Lighting. 번호를 한 칸씩 민다.
      if (spaceN) spaceN.textContent = "3";
      if (lightingN) lightingN.textContent = "4";
      steps.classList.add("has-venue");
      renderVenues(cfg);
      if (spaceWrap) spaceWrap.innerHTML = "";        // Venue 선택 후 채움
      steps.classList.add("is-venue-active");
      wireVenues();
    } else {
      // 기존 3단계 흐름: Project → Space → Lighting.
      if (spaceN) spaceN.textContent = "2";
      if (lightingN) lightingN.textContent = "3";
      if (venueWrap) venueWrap.innerHTML = "";        // 이전 venue 선택 잔재 제거
      if (cfg) renderSpaces(cfg);
      else if (spaceWrap) spaceWrap.innerHTML = defaultSpacesHTML;   // 정적 마크업 복원
      steps.classList.add("is-space-active");
      wireSpaces();
    }
  });
  // ── 단일 페이지 단계 전환 ────────────────────────────────────────────────
  // 선택폼(.lf-form[data-step="1"])과 설정 위저드(.lfc[data-step="2"])가 같은
  // 페이지에 있고, 패널을 show/hide 로 전환한다(예전엔 light-find-config.html 이동).
  var panels = Array.prototype.slice.call(
    document.querySelectorAll("main [data-step]")
  );

  function showStep(n) {
    var target = null;
    panels.forEach(function (panel) {
      var on = panel.getAttribute("data-step") === String(n);
      panel.hidden = !on;
      if (on) target = panel;
    });
    if (!target) return;
    var hero = document.querySelector(".lf-hero");
    if (hero && typeof hero.scrollIntoView === "function") {
      hero.scrollIntoView({ block: "start" });
    } else {
      window.scrollTo(0, 0);
    }
    if (typeof target.focus === "function") {
      target.setAttribute("tabindex", "-1");
      target.focus({ preventScroll: true });
    }
  }

  // 활성 상태에서 NEXT 클릭 → 선택값을 위저드에 전달하고 설정 위저드(Step 2) 표시.
  //   light-find-config.js 가 lf:configstart 를 받아 조명타입별 세부 스텝(PDF)을 구성.
  if (next) {
    next.addEventListener("click", function () {
      if (!next.classList.contains("is-active")) return;
      document.dispatchEvent(new CustomEvent("lf:configstart", {
        detail: {
          project: selectedLabel(projectOptions),
          venue: selectedLabel(venueWrap),   // Museum/Gallery 외엔 "" (위저드가 무시)
          space: selectedLabel(spaceWrap),
          lighting: selectedLabel(lightingWrap)
        }
      }));
      showStep(2);
    });
  }

  // 설정 위저드(light-find-config.js)가 "선택폼으로 돌아가기" 를 요청하는 경로.
  //   위저드 내부 Step 1 에서 BACK → lf:gostep 이벤트로 페이지 패널을 전환합니다.
  //   (이벤트로 디커플링: 위저드는 내부 단계만 알고, 페이지 전환은 여기서 담당)
  document.addEventListener("lf:gostep", function (e) {
    var n = e.detail && e.detail.step;
    if (n != null) showStep(n);
  });

  /* ------------------------------------------------------------------------
   * INFO 모달 (Figma node 7126:15369)
   *   General light 옵션의 info(ⓘ) 클릭 → 해당 항목 이미지/제목/설명을 모달로.
   *   닫기: × 버튼 · 배경(backdrop) 클릭 · Esc.
   * ---------------------------------------------------------------------- */
  var modal = document.getElementById("lf-info-modal");
  if (modal) {
    var modalImg = modal.querySelector("[data-modal-img]");
    var modalTitle = modal.querySelector("[data-modal-title]");
    var modalDesc = modal.querySelector("[data-modal-desc]");
    var lastFocus = null;

    function openModal(trigger) {
      lastFocus = trigger || null;
      if (modalTitle) modalTitle.textContent = trigger.getAttribute("data-title") || "";
      if (modalDesc) modalDesc.textContent = trigger.getAttribute("data-desc") || "";
      if (modalImg) {
        modalImg.setAttribute("src", trigger.getAttribute("data-img") || "");
        modalImg.setAttribute("alt", trigger.getAttribute("data-title") || "");
      }
      modal.classList.add("is-open");
      var closeBtn = modal.querySelector("[data-modal-close]");
      if (closeBtn) closeBtn.focus();
    }
    function closeModal() {
      modal.classList.remove("is-open");
      if (lastFocus && typeof lastFocus.focus === "function") lastFocus.focus();
    }

    // info 트리거: 옵션 선택과 분리하기 위해 클릭 전파 차단
    document.querySelectorAll("[data-info]").forEach(function (info) {
      info.addEventListener("click", function (e) {
        e.stopPropagation();
        openModal(info);
      });
      info.addEventListener("keydown", function (e) {
        if (e.key === "Enter" || e.key === " " || e.key === "Spacebar") {
          e.preventDefault();
          e.stopPropagation();
          openModal(info);
        }
      });
    });

    // 닫기: × 버튼 / 배경 클릭 / Esc
    modal.querySelectorAll("[data-modal-close]").forEach(function (btn) {
      btn.addEventListener("click", closeModal);
    });
    modal.addEventListener("click", function (e) {
      if (e.target === modal) closeModal();          // 카드 바깥(backdrop) 클릭
    });
    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape" && modal.classList.contains("is-open")) closeModal();
    });
  }
})();
